### ISSUE TITLE
prototype naming convention

### ISSUE THREAD

**Issue by Cyd007** [0tho/MM-Core#1]
I read your message and the article about prototype and it seems like a good idea for setting up templates for many items and blocks that are going to use that set of configurations. 

However, I feel the naming convention "prototype" may confuse user on what this attribute can do. Also "onlyPrototype" again may confuse people what this means as well.  I read the info you provide and I understood it completely, but for someone who looking for a "one word sums it all what they want"  I feel they will over look these. 

These are the words I would suggest to use instead and use if possible:

"prototype" = "inherit" 
"onlyPrototype" = "nameInherit" 

It doesn't have to be these but having a naming convention that sums up what it does may make it additionally easier for people to use, like "tools" = "ax".

**Comment by marcel0ll** [comment]
I liked "inherit".
what about:

"onlyPrototype": true -> "isTemplate": true

**Comment by Cyd007** [comment]
That does sounds a lot better actually.  It makes it more obvious what it is, let alone what the set of configurations are going be for.  Like if you where going to create more types of ingots, just have a "isTemplate" of ingots. 

Thumbs up. I like it. 

Keep up the good work. :-)

**Comment by DarkBlade177** [comment]
Seems good, what version is this mod for? 1.7.10 or 1.10

**Comment by marcel0ll** [comment]
It will be for 1.10

**Comment by marcel0ll** [comment]
Close issue with [commit](https://github.com/0tho/MM-Core/commit/140721f2789c7018e5ed44f744d0dec709c7979d)

The interface and readme were updated
